// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv'
import { join, resolve } from 'path'
import { defineConfig } from 'prisma/config'

const envFile = resolve(join(__dirname, '../../../../apps/rem-ids/.env'))
config({ path: envFile })

export default defineConfig({
  schema: './schema.prisma',
  migrations: {
    path: './migrations'
  },
  datasource: {
    url: process.env.DATABASE_URL as string
  }
})
