version: '3.9'

services:
  remlore-redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - remlore

  remlore-api-postgres:
    image: postgres:17
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: remlore-api
      POSTGRES_USER: ${REM_API_DB_USER}
      POSTGRES_PASSWORD: ${REM_API_DB_PASSWORD}
    volumes:
      - ./tmp/remlore-api:/var/lib/postgresql@17/data
    networks:
      - remlore

  remlore-ids-postgres:
    image: postgres:17
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: remlore-ids
      POSTGRES_USER: ${REM_API_DB_USER}
      POSTGRES_PASSWORD: ${REM_IDS_DB_PASSWORD}
    volumes:
      - ./tmp/remlore-ids:/var/lib/postgresql/data
    networks:
      - remlore

networks:
  remlore:


volumes:
  remlore-api:
  remlore-ids:
